package com.training.demo;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Full vocabulary lists for English for IT units (counts match unit card labels).
 */
public final class EnglishItVocabulary {

    private static final Map<String, List<EnglishItLectureContent.VocabEntry>> BY_UNIT = new LinkedHashMap<>();

    static {
        registerAll();
    }

    private EnglishItVocabulary() {
    }

    public static List<EnglishItLectureContent.VocabEntry> getVocabulary(String unitId) {
        return List.copyOf(BY_UNIT.getOrDefault(unitId, List.of()));
    }

    public static int count(String unitId) {
        return BY_UNIT.getOrDefault(unitId, List.of()).size();
    }

    public static List<String> sampleTerms(String unitId, int limit) {
        return getVocabulary(unitId).stream()
                .limit(limit)
                .map(EnglishItLectureContent.VocabEntry::term)
                .toList();
    }

    private static void registerAll() {
        put("welcome", 24,
                "hardware", "Physical parts of a computer",
                "software", "Programs that run on a device",
                "user interface (UI)", "Visual part users interact with",
                "login", "Signing into a system",
                "download", "Copying data from the internet",
                "upload", "Sending data to a server",
                "password", "Secret word for authentication",
                "username", "Name used to identify an account",
                "click", "Press a mouse button to select",
                "keyboard", "Device for typing text",
                "monitor", "Screen that displays output",
                "mouse", "Pointing device for navigation",
                "folder", "Container for organizing files",
                "file", "A named unit of stored data",
                "save", "Store changes to disk",
                "open", "Start or access a file or app",
                "close", "Exit a window or application",
                "install", "Set up software on a machine",
                "restart", "Shut down and start the computer again",
                "browser", "Program for viewing websites",
                "email", "Electronic mail messages",
                "icon", "Small picture representing an action",
                "desktop", "Main screen area of an OS",
                "laptop", "Portable personal computer");

        put("operating-systems", 28,
                "boot up", "Start a computer",
                "shut down", "Turn off a computer safely",
                "file system", "Structure storing files and folders",
                "permissions", "Rules about who can access files",
                "task manager", "Tool showing running processes",
                "update", "New version fixing or improving software",
                "driver", "Software controlling hardware devices",
                "memory (RAM)", "Temporary workspace for running programs",
                "processor (CPU)", "Chip that executes instructions",
                "registry", "Database of system settings (Windows)",
                "kernel", "Core part of an operating system",
                "process", "A running program instance",
                "thread", "Smaller unit of work inside a process",
                "crash", "When a program stops unexpectedly",
                "freeze", "When the system stops responding",
                "reboot", "Restart the computer",
                "administrator", "User with full system rights",
                "path", "Location of a file in folders",
                "extension", "Suffix showing file type (.txt, .java)",
                "recycle bin", "Place for deleted files before removal",
                "shortcut", "Quick link to a file or program",
                "settings", "Configuration options for the OS",
                "notification", "Alert message from the system",
                "background process", "Program running without visible window",
                "disk space", "Available storage on a drive",
                "format", "Prepare a drive with a file system",
                "partition", "Separate section of a hard drive",
                "reproduce", "Make a problem happen again for testing");

        put("software-applications", 26,
                "spreadsheet", "App for tables, numbers, and formulas",
                "word processor", "App for writing documents",
                "presentation", "Slide-based software (e.g. PowerPoint)",
                "toolbar", "Row of buttons for common actions",
                "menu bar", "Top row of application menus",
                "shortcut", "Quick keyboard combination",
                "sync", "Keep data the same across devices",
                "cloud storage", "Online space for saving files",
                "attachment", "File sent with an email",
                "browser tab", "Separate page within a browser",
                "bookmark", "Saved link to a webpage",
                "search box", "Field for finding content in an app",
                "undo", "Reverse the last action",
                "redo", "Repeat an undone action",
                "copy", "Duplicate selected content",
                "paste", "Insert copied content",
                "cut", "Remove and copy content to clipboard",
                "zoom in", "Make content appear larger",
                "zoom out", "Make content appear smaller",
                "print", "Send a document to a printer",
                "share", "Give others access to a file",
                "collaborate", "Work on a document together",
                "template", "Pre-designed document layout",
                "macro", "Recorded sequence of actions",
                "plugin", "Add-on that extends an application",
                "version", "Number identifying a software release");

        put("tech-support", 29,
                "ticket", "Recorded support request",
                "troubleshoot", "Find the cause of a problem",
                "workaround", "Temporary fix",
                "escalate", "Pass issue to higher support level",
                "SLA", "Service Level Agreement for response time",
                "incident", "Unplanned service interruption",
                "priority", "Urgency level of a ticket",
                "severity", "Impact level of an issue",
                "screenshot", "Image capture of the screen",
                "error message", "Text describing what went wrong",
                "log file", "Record of system events",
                "remote access", "Connecting to a user's machine remotely",
                "reset password", "Issue a new login credential",
                "knowledge base", "Collection of support articles",
                "FAQ", "Frequently Asked Questions",
                "first-line support", "Initial help desk contact",
                "second-line support", "Specialist technical team",
                "on hold", "Waiting while issue is investigated",
                "follow up", "Check back with the user later",
                "resolved", "Problem has been fixed",
                "pending", "Waiting for user or third party",
                "duplicate ticket", "Same issue reported twice",
                "root cause", "Underlying reason for a problem",
                "customer satisfaction", "Measure of user happiness with support",
                "call back", "Phone the user again",
                "live chat", "Real-time text support channel",
                "self-service", "User fixes issue using guides",
                "outage", "Service unavailable to many users",
                "status page", "Public page showing system health");

        put("introduction-to-software", 32,
                "application", "Software designed for end users",
                "release", "Published version of software",
                "patch", "Small update fixing issues",
                "open source", "Code available for public use and modification",
                "proprietary", "Software owned by a vendor",
                "deployment", "Putting software into a live environment",
                "license", "Legal terms for using software",
                "version number", "Identifier such as 1.0 or 2.3.1",
                "bug fix", "Correction of a software defect",
                "feature", "New capability in a product",
                "rollback", "Return to a previous version",
                "staging", "Pre-production test environment",
                "production", "Live environment for real users",
                "build", "Compiled package ready to deploy",
                "repository", "Storage for source code",
                "dependency", "External library a project needs",
                "configuration", "Settings that control behavior",
                "installer", "Program that sets up software",
                "uninstall", "Remove software from a system",
                "changelog", "List of changes in a release",
                "beta", "Pre-release version for testing",
                "alpha", "Early internal test version",
                "end user", "Person who uses the finished product",
                "vendor", "Company that sells software",
                "SaaS", "Software as a Service — cloud subscription model",
                "on-premises", "Software installed on company servers",
                "migration", "Moving data or apps to a new system",
                "compatibility", "Ability to work with other systems",
                "maintenance", "Ongoing updates and support",
                "roadmap", "Plan for future product development",
                "technical debt", "Cost of quick fixes that need rework later",
                "hotfix", "Urgent patch for a critical issue");

        put("it-careers", 30,
                "developer", "Person who writes and maintains code",
                "stakeholder", "Person with interest in project outcomes",
                "deadline", "Date work must be completed",
                "onboarding", "Process of joining a new team",
                "portfolio", "Collection of your best work",
                "mentor", "Experienced guide for your growth",
                "internship", "Temporary training position",
                "junior developer", "Entry-level software role",
                "senior developer", "Experienced technical lead",
                "team lead", "Person coordinating a small team",
                "scrum master", "Facilitator of agile ceremonies",
                "product owner", "Defines priorities for the team",
                "business analyst", "Bridges business and technical needs",
                "DevOps engineer", "Focuses on deployment and infrastructure",
                "QA engineer", "Tests software quality",
                "UI/UX designer", "Designs user experience and interfaces",
                "CV / resume", "Document summarizing your experience",
                "interview", "Meeting to assess a job candidate",
                "job description", "Official list of role requirements",
                "salary", "Payment for employment",
                "remote work", "Working from outside the office",
                "hybrid work", "Mix of office and remote days",
                "promotion", "Advancement to a higher role",
                "resignation", "Formal notice of leaving a job",
                "reference", "Person who confirms your work history",
                "soft skills", "Communication and teamwork abilities",
                "hard skills", "Technical abilities such as coding",
                "certification", "Official proof of a qualification",
                "networking", "Building professional contacts",
                "career path", "Long-term progression in your field");

        put("the-internet", 34,
                "internet", "Global network of connected computers",
                "domain", "Human-readable website name",
                "DNS", "Maps domain names to IP addresses",
                "HTTPS", "Secure encrypted web protocol",
                "HTTP", "Standard protocol for web pages",
                "bandwidth", "Capacity of a network connection",
                "latency", "Delay before data arrives",
                "firewall", "Filters network traffic for security",
                "IP address", "Numeric identifier of a device",
                "URL", "Full web address in the browser",
                "browser cache", "Stored copies of web resources",
                "cookie", "Small data file saved by websites",
                "proxy", "Intermediate server between user and internet",
                "VPN", "Encrypted tunnel for secure remote access",
                "Wi-Fi", "Wireless local network connection",
                "router", "Device forwarding traffic between networks",
                "modem", "Connects home network to ISP",
                "ISP", "Internet Service Provider",
                "upload speed", "Rate of sending data online",
                "download speed", "Rate of receiving data online",
                "ping", "Test of network response time",
                "timeout", "Connection failed due to no response",
                "SSL certificate", "Proof enabling HTTPS encryption",
                "web server", "Machine that hosts websites",
                "API endpoint", "URL where a service accepts requests",
                "cloud", "Remote servers accessed over the internet",
                "streaming", "Playing media while downloading",
                "browser extension", "Add-on for extra browser features",
                "pop-up", "Unexpected small window on a webpage",
                "phishing site", "Fake site stealing credentials",
                "search engine", "Tool for finding web content",
                "social media", "Platforms for online interaction",
                "e-commerce", "Buying and selling online",
                "IoT", "Internet of Things — connected devices");

        put("computer-ethics", 27,
                "data privacy", "Protecting personal information",
                "consent", "Freely given permission for data use",
                "compliance", "Following laws and regulations",
                "copyright", "Legal right to control copying",
                "plagiarism", "Using others' work without credit",
                "intellectual property", "Creations protected by law",
                "GDPR", "EU data protection regulation",
                "anonymize", "Remove identifying details from data",
                "pseudonymize", "Replace identities with codes",
                "data breach", "Unauthorized access to personal data",
                "whistleblowing", "Reporting unethical or illegal acts",
                "transparency", "Openness about how data is used",
                "accountability", "Taking responsibility for decisions",
                "fair use", "Limited legal use of copyrighted material",
                "open license", "Permission to reuse with conditions",
                "digital footprint", "Trail of data you leave online",
                "surveillance", "Monitoring of user activity",
                "algorithmic bias", "Unfair outcomes from automated systems",
                "informed consent", "User understands and agrees clearly",
                "opt in", "Choose to participate",
                "opt out", "Choose to stop participating",
                "terms of service", "Rules for using a platform",
                "ethical hacking", "Authorized security testing",
                "responsible disclosure", "Reporting vulnerabilities safely",
                "green computing", "Reducing environmental IT impact",
                "e-waste", "Discarded electronic equipment",
                "digital rights", "Freedoms and protections online");

        put("programming-languages", 31,
                "compiled", "Translated to machine code before running",
                "interpreted", "Executed by a runtime line by line",
                "syntax", "Grammar rules of a language",
                "framework", "Structured libraries and conventions",
                "runtime", "Environment that executes code",
                "paradigm", "Programming style (OOP, functional, etc.)",
                "object-oriented", "Organizing code around objects",
                "functional", "Style using functions and immutability",
                "static typing", "Types checked at compile time",
                "dynamic typing", "Types checked at runtime",
                "garbage collection", "Automatic memory management",
                "pointer", "Reference to a memory address",
                "library", "Reusable pre-written code",
                "package manager", "Tool for installing dependencies",
                "IDE", "Integrated Development Environment",
                "compiler", "Translates source code to executable",
                "interpreter", "Runs code without separate compile step",
                "bytecode", "Intermediate code for virtual machines",
                "virtual machine", "Runtime simulating a computer",
                "cross-platform", "Runs on multiple operating systems",
                "legacy language", "Older language still in maintenance use",
                "scripting language", "Language for automation tasks",
                "low-level language", "Close to machine instructions",
                "high-level language", "Closer to human-readable logic",
                "API binding", "Language wrapper for an external API",
                "ecosystem", "Community, tools, and libraries around a language",
                "performance", "Speed and efficiency of execution",
                "concurrency", "Handling multiple tasks at once",
                "memory leak", "Unused memory not released",
                "standard library", "Built-in modules of a language",
                "syntax error", "Code that breaks language grammar rules");

        put("networking", 33,
                "router", "Forwards data between networks",
                "switch", "Connects devices within a local network",
                "packet", "Small unit of transmitted data",
                "subnet", "Subdivision of a network",
                "DNS", "Resolves names to IP addresses",
                "topology", "Layout of network connections",
                "LAN", "Local Area Network",
                "WAN", "Wide Area Network covering large areas",
                "MAC address", "Hardware identifier of a network card",
                "gateway", "Entry point between networks",
                "port", "Number identifying a service on a host",
                "protocol", "Rules for data communication",
                "TCP", "Reliable connection-oriented protocol",
                "UDP", "Fast connectionless protocol",
                "ICMP", "Protocol for network diagnostic messages",
                "NAT", "Network Address Translation",
                "DHCP", "Automatically assigns IP addresses",
                "VLAN", "Virtual separated network segment",
                "fiber optic", "High-speed cable using light signals",
                "Ethernet", "Common wired LAN technology",
                "wireless access point", "Device providing Wi-Fi",
                "packet loss", "Data that fails to reach destination",
                "jitter", "Variation in packet arrival time",
                "throughput", "Actual data transfer rate achieved",
                "load balancer", "Distributes traffic across servers",
                "traceroute", "Tool showing path packets take",
                "ping (network)", "Test if a host is reachable",
                "hostname", "Name assigned to a device on a network",
                "subnet mask", "Defines which part of IP is network vs host",
                "CIDR", "Compact notation for IP ranges",
                "network interface", "Hardware or virtual network connection",
                "broadcast", "Message sent to all devices on a segment",
                "unicast", "Message sent to one specific device");

        put("it-slang", 22,
                "sync up", "Meet briefly to align on progress",
                "ping", "Send a quick message to someone",
                "blocker", "Issue stopping your work",
                "ASAP", "As soon as possible",
                "bandwidth (metaphor)", "Available time or mental capacity",
                "circle back", "Return to a topic later",
                "deep dive", "Detailed investigation or discussion",
                "heads down", "Focused work with few interruptions",
                "LGTM", "Looks Good To Me — approval in reviews",
                "WIP", "Work In Progress",
                "ETA", "Estimated Time of Arrival / completion",
                "FYI", "For Your Information",
                "IMO / IMHO", "In My (Humble) Opinion",
                "out of the loop", "Not informed about something",
                "touch base", "Make brief contact with someone",
                "move the needle", "Create meaningful progress",
                "low-hanging fruit", "Easy wins to implement first",
                "firefighting", "Urgently fixing production problems",
                "on the same page", "In agreement about a plan",
                "rubber duck", "Explain code aloud to find bugs",
                "ship it", "Deploy or release the work",
                "stand-up", "Short daily team status meeting");

        put("cybersecurity", 36,
                "encryption", "Encoding data to prevent unauthorized reading",
                "authentication", "Verifying identity",
                "authorization", "Checking what a user may access",
                "phishing", "Trick to steal credentials",
                "vulnerability", "Weakness that may be exploited",
                "breach", "Unauthorized access to protected data",
                "malware", "Malicious software",
                "ransomware", "Malware that locks data for payment",
                "spyware", "Software that secretly monitors users",
                "trojan", "Malware disguised as legitimate software",
                "MFA", "Multi-Factor Authentication",
                "2FA", "Two-Factor Authentication",
                "hashing", "One-way transformation of data",
                "salt", "Random data added before hashing passwords",
                "zero-day", "Exploit unknown to the vendor",
                "penetration test", "Authorized simulated attack",
                "SOC", "Security Operations Center",
                "SIEM", "System collecting security event logs",
                "incident response", "Organized reaction to security events",
                "threat actor", "Person or group posing a security risk",
                "attack surface", "All points where a system can be attacked",
                "least privilege", "Giving minimum access needed",
                "defense in depth", "Multiple layers of security controls",
                "CIA triad", "Confidentiality, Integrity, Availability",
                "DDoS", "Distributed Denial of Service attack",
                "brute force", "Trying many passwords rapidly",
                "credential stuffing", "Reusing stolen passwords elsewhere",
                "security patch", "Fix for a known vulnerability",
                "hardening", "Reducing system vulnerabilities",
                "air gap", "Physical isolation from networks",
                "token", "Digital proof of authentication",
                "certificate authority", "Issuer of digital certificates",
                "man-in-the-middle", "Attacker intercepting communication",
                "social engineering", "Manipulating people to reveal secrets",
                "red team", "Group simulating attacks",
                "blue team", "Group defending systems");

        put("programmers", 38,
                "refactor", "Improve code structure without changing behavior",
                "breakpoint", "Pause point when debugging",
                "legacy code", "Old code difficult to change",
                "merge conflict", "Git cannot auto-combine changes",
                "pull request", "Proposal to merge code changes",
                "code review", "Peer examination of code changes",
                "commit", "Saved snapshot in version control",
                "branch", "Separate line of development",
                "clone", "Copy a repository locally",
                "push", "Upload commits to remote repository",
                "pull", "Download changes from remote",
                "stash", "Temporarily save uncommitted changes",
                "cherry-pick", "Apply specific commit to another branch",
                "rebase", "Replay commits on a new base",
                "unit test", "Automated test of a small code unit",
                "integration test", "Test of combined components",
                "mock", "Fake object for testing",
                "stub", "Minimal fake implementation",
                "debug", "Find and fix defects",
                "stack trace", "Report of function calls at error time",
                "log statement", "Code writing diagnostic output",
                "variable", "Named storage for a value",
                "constant", "Value that should not change",
                "method", "Named block of reusable code",
                "class", "Blueprint for objects in OOP",
                "interface", "Contract defining required methods",
                "inheritance", "Deriving a class from a parent",
                "polymorphism", "Same interface, different implementations",
                "encapsulation", "Hiding internal object details",
                "naming convention", "Standard rules for naming code",
                "technical debt", "Future cost of quick shortcuts",
                "spaghetti code", "Tangled hard-to-follow code",
                "boilerplate", "Repetitive code required by a framework",
                "dead code", "Unused code never executed",
                "race condition", "Bug from timing of parallel tasks",
                "null pointer", "Reference to missing object",
                "compile error", "Code that fails to build",
                "runtime error", "Failure while program is running");

        put("artificial-intelligence", 35,
                "machine learning", "Systems that learn patterns from data",
                "dataset", "Collection of data for training or testing",
                "inference", "Running a trained model on new data",
                "neural network", "Model inspired by brain structure",
                "bias", "Systematic unfairness in outcomes",
                "training", "Process of teaching a model from data",
                "validation", "Checking model on held-out data",
                "overfitting", "Model memorizes training data too closely",
                "underfitting", "Model too simple to capture patterns",
                "feature", "Input variable used by a model",
                "label", "Correct answer in supervised learning",
                "supervised learning", "Learning from labeled examples",
                "unsupervised learning", "Finding patterns without labels",
                "classification", "Predicting categories",
                "regression", "Predicting numeric values",
                "clustering", "Grouping similar data points",
                "hyperparameter", "Configuration set before training",
                "epoch", "One full pass through training data",
                "gradient descent", "Optimization algorithm for training",
                "loss function", "Measures how wrong predictions are",
                "accuracy", "Percentage of correct predictions",
                "precision", "Correct positive predictions among all positives",
                "recall", "Correct positives found among actual positives",
                "F1 score", "Balance of precision and recall",
                "NLP", "Natural Language Processing",
                "computer vision", "AI interpreting images or video",
                "LLM", "Large Language Model",
                "prompt", "Input text given to an AI model",
                "fine-tuning", "Adapting a pre-trained model to a task",
                "transfer learning", "Reusing knowledge from one task on another",
                "explainability", "Ability to understand model decisions",
                "hallucination", "AI generating false information",
                "model drift", "Performance degrading over time",
                "ground truth", "Verified correct data for comparison",
                "annotation", "Human labeling of training data");

        put("qa", 30,
                "test case", "Documented steps to verify behavior",
                "acceptance criteria", "Conditions for story completion",
                "defect", "Flaw that does not meet expectations",
                "regression", "New change breaks existing functionality",
                "automation", "Running tests with scripts",
                "manual testing", "Human execution of test steps",
                "smoke test", "Quick check that core features work",
                "sanity test", "Narrow check after a small change",
                "exploratory testing", "Simultaneous learning and testing",
                "test plan", "Document describing testing approach",
                "test suite", "Collection of related test cases",
                "expected result", "What should happen if software works",
                "actual result", "What really happened during the test",
                "reproduction steps", "Steps to make a bug appear again",
                "severity", "Impact of a defect on the system",
                "priority", "Urgency of fixing a defect",
                "blocking defect", "Issue that stops release",
                "sign-off", "Formal approval to release",
                "staging environment", "Pre-production test system",
                "UAT", "User Acceptance Testing",
                "boundary value", "Test at edge of valid input range",
                "equivalence partition", "Group of inputs treated the same",
                "negative testing", "Testing invalid or unexpected input",
                "positive testing", "Testing valid expected input",
                "test data", "Input values used during testing",
                "flaky test", "Test that sometimes passes, sometimes fails",
                "CI pipeline", "Automated build and test on each change",
                "bug report", "Document describing a found defect",
                "retest", "Verify a fix for a reported defect",
                "exit criteria", "Conditions required to stop testing");
    }

    private static void put(String unitId, int expectedCount, String... termAndDef) {
        if (termAndDef.length % 2 != 0) {
            throw new IllegalArgumentException("Vocab pairs must be even for " + unitId);
        }
        List<EnglishItLectureContent.VocabEntry> list = new ArrayList<>();
        for (int i = 0; i < termAndDef.length; i += 2) {
            list.add(new EnglishItLectureContent.VocabEntry(termAndDef[i], termAndDef[i + 1]));
        }
        if (list.size() != expectedCount) {
            throw new IllegalStateException(unitId + " vocab count " + list.size() + " != " + expectedCount);
        }
        BY_UNIT.put(unitId, list);
    }
}
